permalink: pretty

exclude:
- ".sass-cache"
- "Gemfile"
- "Gemfile.lock"
- "html-minifier.json"
- "LICENSE.md"
- "package.json"
- "package-lock.json"
- "README.md"
- "node_modules/"
- "src/"

sass:
  style: compressed
