# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

exclude:
- "node_modules"
- "src"
- "CNAME"
- "gulpfile.js"
- "LICENSE.md"
- "package.json"
- "README.md"
