name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Disable gem docs
        run: 'echo "gem: --no-document" > ~/.gemrc'

      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"

      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Install bundler dependencies
        run: bundle install --deployment --jobs=3 --retry=3 --clean

      - name: Run tests
        run: npm test
